########################################### HEATING ############################################

- platform: mqtt
  name: "Basement Heating"
  state_topic: "shellies/shelly1-E098068CE35F/relay/0"
  command_topic: "shellies/shelly1-E098068CE35F/relay/0/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: false

- platform: mqtt
  name: "Ground Floor Heating"
  state_topic: "shellies/shelly1-E098068CCDF2/relay/0"
  command_topic: "shellies/shelly1-E098068CCDF2/relay/0/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: false

- platform: mqtt
  name: "Upstairs Heating"
  state_topic: "shellies/shelly1-E098068CDF25/relay/0"
  command_topic: "shellies/shelly1-E098068CDF25/relay/0/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: false
