= Home Assistant Config by Yorgos

:toc: auto

This repo exposes the Home Assistant functionality I've built up over the years
that I think is worth sharing with the world. (i.e. this isn't "everything", 
nor is this repo somehow linked (today) to my actual running home assistant 
instance). Docs are currently work-in-progress, but the configuration is 100% 
functional. 

== Roller Shutters

My current solution for roller shutters, included in this repo, was
put in place a short while prior to the launch of Shelly 1, so they
involve a setup based on Sonoff T1 switches, running Tasmota.

The switches are connected to the MQTT server and they are controlled
via MQTT through Home Assistant, with the config you'll find in:

* link:covers/covers.yaml[covers/covers.yaml]
* link:automations/covers.yaml[automations/covers.yaml]

The main idea is that the Home Assistant **cover** controls produce MQTT
commands and the **automations** are then responsible for triggering
the suitable relay.

This is a working setup that I am fairly happy with, considering the
alternative of stripping everything and starting over, but I would do
things differently next time round...

I am not **at all** happy with these hardware switches, and I also don't have position controls available with this approach (though I
have _timed_ how long some positions take, in some link:scripts.yaml[scripts]).

The good news is that a **much better** setup is nowadays possible,
with Shelly 2.5 and their "Roller Shutters" function! You can find
a link:https://gsaslis.github.io/posts/smart-roller-shutters[detailed How-to here].

== Garage Door

Read more on https://gsaslis.github.io/posts/my-smart-garage-door[my blog] !

== Thermostats

TODO: https://github.com/gsaslis/home-assistant-config/issues/3

== Camera Movement Automation

TODO: https://github.com/gsaslis/home-assistant-config/issues/2

== Water Leak Sensor

TODO: https://github.com/gsaslis/home-assistant-config/issues/1

== Meeting Light

TODO: https://github.com/gsaslis/home-assistant-config/issues/5

== Mosquito Repellent 

TODO: https://github.com/gsaslis/home-assistant-config/issues/6

== Watering 

TODO: https://github.com/gsaslis/home-assistant-config/issues/7

== Lights Automation

TODO: https://github.com/gsaslis/home-assistant-config/issues/8

== Rain Sensor

TODO: https://github.com/gsaslis/home-assistant-config/issues/9

== Power Consumption

TODO: https://github.com/gsaslis/home-assistant-config/issues/10

== Cameras

TODO: https://github.com/gsaslis/home-assistant-config/issues/11

== Speed Test

TODO: https://github.com/gsaslis/home-assistant-config/issues/12

== Text-to-speech with mimic3

TODO: https://github.com/gsaslis/home-assistant-config/issues/13

== Apple Home integration

TODO: https://github.com/gsaslis/home-assistant-config/issues/14
