- platform: group
  name: Outdoor
  unique_id: outdoor
  entities:
    - light.garden_steps
    - light.garden_path
#    Switched to on/off triggered by movement
#    - light.kitchen_patio_lights
    - light.main_entrance_1
      # don't need both   - light.main_entrance_2
      # fwtakia    - light.north_balcony
    - light.east_bedroom_balcony
